name: ECS Fargate Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/ecs-fargate-app
          VERSION=${{ github.sha }}
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      # 4. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # <-- Change to your AWS region if needed

      # 5. Install Node.js (if not installed) and CDK CLI
      - name: Install Node.js & AWS CDK
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g aws-cdk

      # 6. Deploy using CDK
      - name: CDK Deploy
        run: |
          pip install --user -r requirements.txt
          cdk deploy --app "python app.py" --require-approval never
